# Generated by Django 5.0 on 2023-12-07 15:04

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission

def create_groups_and_permissions(apps, schema_editor):
    # Créer le groupe
    client_group, created = Group.objects.get_or_create(name='client')
    provider_group,created = Group.objects.get_or_create(name="provider")

class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0039_userpermissions'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
