# Generated by Django 5.0 on 2023-12-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0040_ticket_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermissions',
            options={'permissions': (('user_can_view_all_tickets', 'User can view all tickets'), ('user_can_view_own_tickets', 'User can view own tickets'), ('user_can_view_tickets_where_assigned', 'User can view the tickets where he is assigned.'))},
        ),
    ]
